export const regions = {
  Bronx: [
    'Allerton',
    'Bathgate',
    'Baychester',
    'Bedford Park',
    'Belmont',
    'Bronx River',
    'Bronxdale',
    'Bruckner',
    'Castle Hill',
    'City Island',
    'Claremont',
    'Clason Point',
    'Co-op City',
    'Concourse Village',
    'Concourse',
    'Crotona Park',
    'East Tremont',
    'Eastchester',
    'Edenwald',
    'Fieldston',
    'Fish Bay',
    'Fordham',
    'Harding Park',
    'High Bridge',
    'Hunts Point',
    'Indian Village',
    'Kingsbridge Heights',
    'Kingsbridge',
    'Laconia',
    'Locust Point',
    'Longwood',
    'Marble Hill',
    'Melrose',
    'Morris Heights',
    'Morris Park',
    'Morrisania',
    'Mott Haven',
    'Mount Hope',
    'Norwood',
    'Olinville',
    'Parkchester',
    'Pelham Bay',
    'Pelham Gardens',
    'Pelham Parkway',
    'Port Morris',
    'Riverdale',
    'Silver Beach',
    'Soundview',
    'Spuyten Duyvil',
    'Throgs Neck',
    'Unionport',
    'University Heights',
    'University Heights',
    'Van Cortlandt Village',
    'Van Nest[3][4]',
    'Wakefield',
    'West Farms',
    'Westchester Square',
    'Williamsbridge',
    'Woodlawn'
  ],
  Brooklyn: [
    'Bath Beach',
    'Bay Ridge',
    'Bedford-Stuyvesant',
    'Bensonhurst',
    'Bensonhurst',
    'Bergen Beach',
    'Boerum Hill',
    'Borough Park',
    'Brighton Beach',
    'Brooklyn Heights',
    'Brooklyn Navy Yard',
    'Brownsville',
    'Bushwick',
    'Canarsie',
    'Carroll Gardens',
    'City Line',
    'Clinton Hill',
    'Cobble Hill',
    'Coney Island',
    'Crown Heights',
    'Crown Heights',
    'Cypress Hills',
    'Ditmas Village',
    'DUMBO',
    'Dyker Heights',
    'East Flatbush',
    'East Gravesend',
    'East New York',
    'Erasmus',
    'Farragut',
    'Flatbush',
    'Flatlands',
    'Fort Greene',
    'Fort Hamilton',
    'Fulton Ferry',
    'Fulton Mall',
    'Georgetown',
    'Gerritsen Beach',
    'Gowanus',
    'Gravesend',
    'Gravesend',
    'Greenpoint',
    'Greenwood Heights',
    'Highland Park',
    'Homecrest',
    'Kensington',
    'Kensington',
    'Kings Bay',
    'Kings Highway',
    'Madison',
    'Manhattan Beach',
    'Mapleton',
    'Marine Park',
    'Midwood',
    'Midwood',
    'Mill Basin',
    'Mill Island',
    'New Lots',
    'Ocean Hill',
    'Ocean Hill',
    'Ocean Parkway',
    'Ocean Parkway',
    'Park Slope',
    'Plum Beach',
    'Prospect Heights',
    'Prospect Lefferts Gardens',
    'Red Hook',
    'Remsen Village',
    'Rugby',
    'Sea Gate',
    'Sheepshead Bay',
    'Starrett City',
    'Stuyvesant Heights',
    'Sunset Park',
    'Vinegar Hill',
    'Weeksville',
    'Williamsburg',
    'Windsor Terrace',
    'Wingate'
  ],
  'New York': [
    'Alphabet City',
    'Battery Park City',
    'Chelsea',
    'Chinatown',
    'Chinatown',
    'Clinton',
    'East Harlem',
    'East Village',
    'Financial District',
    'Gramercy Park',
    'Greenwich Village',
    'Hamilton Heights',
    'Harlem',
    'Inwood',
    'Kips Bay',
    'Lenox Hill',
    'Lincoln Square',
    'Little Italy',
    'Lower East Side',
    'Lower East Side',
    'Manhattan Valley',
    'Manhattanville',
    'Midtown',
    'Morningside Heights',
    'Murray Hill',
    'NoHo',
    'Peter Cooper Village',
    'Polo Grounds',
    'Randall’s Island',
    'Roosevelt Island',
    'SoHo',
    'Spanish Harlem',
    'Stuyvesant Town',
    'Sutton Place',
    'TriBeCa',
    'Tudor City',
    'Turtle Bay',
    'Two Bridges',
    'Upper East Side',
    'Upper West Side',
    'Wards Island',
    'Washington Heights',
    'Waterside Plaza',
    'West Village',
    'Yorkville'
  ],
  Queens: [
    'Arverne',
    'Astoria',
    'Auburndale',
    'Baisley Park',
    'Bay Terrace',
    'Bayside',
    'Bayswater',
    'Beechhurst',
    'Belle Harbor',
    'Bellerose',
    'Breezy Point',
    'Briarwood',
    'Brookville',
    'Cambria Heights',
    'College Point',
    'Corona',
    'Cunningham Heights',
    'Ditmars',
    'Douglaston',
    'East Elmhurst',
    'East Flushing',
    'Edgemere',
    'Elmhurst',
    'Far Rockaway',
    'Floral Park',
    'Flushing South',
    'Flushing',
    'Forest Hills',
    'Fresh Meadows',
    'Fresh Pond',
    'Garden Bay',
    'Glen Oaks',
    'Glendale',
    'Hilltop Village',
    'Hollis Hills',
    'Hollis',
    'Holliswood',
    'Howard Beach',
    'Hunters Point',
    'Jackson Heights',
    'Jamaica Estates',
    'Jamaica',
    'Kew Gardens Hills',
    'Kew Gardens',
    'Laurelton',
    'Liberty Park',
    'Linden Hill',
    'Lindenwood',
    'Little Neck',
    'Long Island City',
    'Malba',
    'Maspeth',
    'Meadowmere',
    'Middle Village',
    'Neponsit',
    'New Hyde Park',
    'North Corona',
    'Oakland Gardens',
    'Old Astoria',
    'Ozone Park',
    'Pomonok Houses',
    'Queens Village',
    'Queensboro Hill',
    'Queensbridge',
    'Ravenswood',
    'Rego Park',
    'Richmond Hill',
    'Richmond Hill',
    'Ridgewood',
    'Rochdale Village',
    'Rockaway Park',
    'Rosedale',
    'South Jamaica',
    'South Ozone Park',
    'Springfield Gardens',
    'St. Albans',
    'Steinway',
    'Sunnyside',
    'Tudor Village',
    'Utopia',
    'Whitestone',
    'Willets Point',
    'Woodhaven',
    'Woodside'
  ],
  'Staten Island': [
    'Annadale',
    'Arden Heights',
    'Arlington',
    'Arrochar',
    'Bay Terrace',
    'Bloomfield',
    'Bulls Head',
    'Castleton Corners',
    'Charleston',
    'Chelsea',
    'Clifton',
    'Concord',
    'Dongan Hills',
    'Egbertville',
    'Elm Park',
    'Eltingville',
    'Emerson Hill',
    'Fort Wadsworth',
    'Graniteville',
    'Grant City',
    'Grasmere',
    'Great Kills',
    'Greenridge',
    'Grymes Hill',
    'Huguenot',
    'Livingston',
    'Mariners Harbor',
    'Meiers Corners',
    'Midland Beach',
    'New Brighton',
    'New Dorp',
    'New Springville',
    'Oakwood',
    'Ocean Breeze',
    'Old Town',
    'Pleasant Plains',
    'Port Ivory',
    'Port Richmond',
    'Prince’s Bay',
    'Randall Manor',
    'Richmond Valley',
    'Rosebank',
    'Rossville',
    'Shore Acres',
    'Silver Lake',
    'South Beach',
    'St. George',
    'Stapleton',
    'Sunnyside',
    'Todt Hill',
    'Tompkinsville',
    'Tottenville',
    'Travis',
    'West Brighton',
    'Westerleigh',
    'Woodrow'
  ]
};

export const filterRegion = (neighborhood, properties) =>
  properties.filter(
    property => property.location.neighborhood.trim() === neighborhood
  );
export const filterBorough = (borough, properties) =>
  properties.filter(property => property.location.city.trim() === borough);
